version: '3'

services:
  web:
    build: .
    command: "./wait-for-it.sh db:5432 -- bash -c 'python manage.py migrate && python manage.py loaddata test && python manage.py runserver 0.0.0.0:80'"
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
